map_type: costmap

obstacle_range: 1.5
#raytrace_range: 3.0

transform_tolerance: 0.2

robot_radius: 0.3 
inflation_radius: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
#camera: {sensor_frame: camera, data_type: Image, topic: /udacity_bot/camera1/image_raw, marking: true, clearing: true}
