local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 10.0
   publish_frequency: 10.0
   width: 25.0
   height: 25.0
   resolution: 0.15
   static_map: false
   rolling_window: true
   transform_tolerance: 0.2
